// react-likeable/src/components/like-button.js
import React from 'react';
import './like-button.css';

export default class LikeButton extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isLiked: true,
    };
  }

  toggleLike() {
    this.setState({
      isLiked: !this.state.isLiked
    })
  }

  render(){
    const iconClass = this.state.isLiked ? 'icon liked' : 'icon';
    return (
      <div>
        <h1>Liking a button in react</h1>
        <button 
          onClick={() => this.toggleLike()}
          className={iconClass}>
            ❤ {this.props.nbLikes}
        </button>
      </div>
    )
  }
}

// vue-likeable/src/components/LikeButton.vue
<template>
  <div>
    <button @click="toggleLike()" class="icon" :class="{liked: isLiked}">
      ❤ {{nbLikes}}
    </button>
  </div> 
</template>

<script>
export default {
  props: {
    nbLikes: {
      type: Number,
      default: 0,
    }
  },
  data() {
    return {
      isLiked: true,
    }
  },
  methods: {
    toggleLike: function () {
      this.isLiked = !this.isLiked
    }
  }
}
</script>

<style>

.liked {
  color: red;
}

</style>
