// react-likeable/src/components/like-button.js
import React from 'react';
import './like-button.css';

export default class LikeButton extends React.Component {
  constructor() {
    super();
    this.state = {
      isLiked: true,
    };
  }

  render(){
    const iconClass = this.state.isLiked ? 'icon liked' : 'icon';
    return (
      <div>
        <h1>Liking a button in react</h1>
        <button className={iconClass}>❤</button>
      </div>
    )
  }
}

// ng-likeable/src/app/like-button/like-button.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-like-button',
  templateUrl: './like-button.component.html',
  styleUrls: ['./like-button.component.css']
})
export class LikeButtonComponent implements OnInit {

  public isLiked = true;

  constructor() { }

  ngOnInit() {
  }

}

<div>
  <button 
    class="icon"
    [ngClass]="{liked: isLiked}"
    >❤</button>
</div>
